In [1]:
import pandas as pd

df = pd.DataFrame({
    "sequence": ["ATGCGC", "ATATATTA", "GGCCGGCCAA", "ATGAAATTT", "CGCGAT"],
    "family":   ["kinase", "receptor", "kinase", "receptor", "channel"],
})
df

     sequence    family
0      ATGCGC    kinase
1    ATATATTA  receptor
2  GGCCGGCCAA    kinase
3   ATGAAATTT  receptor
4      CGCGAT   channel

In [4]:
print(df.shape)
print(df.head(2))
print(df.family)

(5, 2)
   sequence    family
0    ATGCGC    kinase
1  ATATATTA  receptor
0      kinase
1    receptor
2      kinase
3    receptor
4     channel
Name: family, dtype: str

In [5]:
df["length"] = df["sequence"].str.len()
df

     sequence    family  length
0      ATGCGC    kinase       6
1    ATATATTA  receptor       8
2  GGCCGGCCAA    kinase      10
3   ATGAAATTT  receptor       9
4      CGCGAT   channel       6

In [6]:
def gc_content(seq):
    return (seq.count("G") + seq.count("C")) / len(seq)

df["gc"] = df["sequence"].apply(gc_content)
df

     sequence    family  length        gc
0      ATGCGC    kinase       6  0.666667
1    ATATATTA  receptor       8  0.000000
2  GGCCGGCCAA    kinase      10  0.800000
3   ATGAAATTT  receptor       9  0.111111
4      CGCGAT   channel       6  0.666667

In [7]:
df["family"].value_counts()

family
kinase      2
receptor    2
channel     1
Name: count, dtype: int64

In [8]:
df[df["gc"]>0.5]

     sequence   family  length        gc
0      ATGCGC   kinase       6  0.666667
2  GGCCGGCCAA   kinase      10  0.800000
4      CGCGAT  channel       6  0.666667

In [9]:
df.groupby("family")["length"].mean()

family
channel     6.0
kinase      8.0
receptor    8.5
Name: length, dtype: float64

In [10]:
df[df["family"]=="receptor"]

    sequence    family  length        gc
1   ATATATTA  receptor       8  0.000000
3  ATGAAATTT  receptor       9  0.111111

In [12]:
df.groupby("family")["gc"].mean()

family
channel     0.666667
kinase      0.733333
receptor    0.055556
Name: gc, dtype: float64

In [13]:
df.groupby("family")["gc"].agg(["mean", "max"])

              mean       max
family
channel   0.666667  0.666667
kinase    0.733333  0.800000
receptor  0.055556  0.111111

In [14]:
[m for m in dir(df["gc"]) if not m.startswith("_")]

['T',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']